replicaCount: 1
service:
  http: 80
  tls: 443
ports:
  http: 10000
  tls: 10001
namespace:
  create: true
  name: debug
serviceAccount:
  create: true
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  targetMemoryUtilizationPercentage: 75
tlsEnabled: false
ingress:
  enabled: true
  ingressClass: 'istio'
  gateway: 'ivanticloud-default-gateway'
  gatewayNamespace: 'istio-system'
  routePrefix: '/api'
  hosts: 
    - host: 'testarossa-sfc.ivanticlouddev.com'
      paths:
        - name: "hello-world"
          route: "hello"
        - name: "auth"
          route: "auth"
        - name: "login-route"
          route: "login"
        - name: "validate-route"
          route: "validate"
        - name: "debug-route"
          route: "debug"
